export const KINESIOLOGY_TITLES = [
  "LICENCIADO/A EN KINESIOLOGÍA Y FISIATRÍA",
  "LICENCIADO/A EN KINESIOLOGÍA",
  "KINESIÓLOGO/A",
  "KINESIÓLOGO/A FISIATRA",
  "FISIOTERAPEUTA",
  "LICENCIADO/A EN KINESIOLOGÍA, FISIATRÍA Y TERAPIA FÍSICA",
  "LICENCIATURA EN KINESIOLOGÍA Y FISIATRÍA",
  "LICENCIADO/A EN KINESIOLOGÍA Y FISIOTERAPIA",
  "OTRO",
];

export default KINESIOLOGY_TITLES;
