import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { CheckCircle2, Clock3, Download, FileX2, Mail, MapPin, Phone, Trash2, X } from "lucide-react";
import { DeclarationData } from "../types";
import { deleteLibreDeudaRequest, loadServerRecord, loadServerRecords, notifyLibreDeudaResolution } from "../api";
import RecordPhoto from "./RecordPhoto";

type Props = { declarations: DeclarationData[]; onUpdate: (data: DeclarationData) => void | Promise<DeclarationData | void>; onClose: () => void };
const date = (value?: string) => {
  if (!value) return "—";
  const iso = String(value).match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return `${iso[3]}/${iso[2]}/${iso[1]}`;
  return new Intl.DateTimeFormat("es-AR", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date(value));
};
const dateTime = (value?: string) => value ? new Intl.DateTimeFormat("es-AR", { timeZone: "America/Argentina/Buenos_Aires", dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—";
const argentinaNow = () => {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Argentina/Buenos_Aires', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).formatToParts(new Date());
  const values = Object.fromEntries(parts.filter(part => part.type !== 'literal').map(part => [part.type, part.value]));
  return values.year + "-" + values.month + "-" + values.day + "T" + values.hour + ":" + values.minute + ":" + values.second + "-03:00";
};
const libreDeudaVenceAt = (request?: DeclarationData["libreDeudaSolicitud"]) => {
  if (!request || request.estado !== "APROBADO") return "";
  const approvalDate = request.revisadoAt;
  if (!approvalDate) return request.venceAt || "";
  const expiry = new Date(approvalDate);
  expiry.setDate(expiry.getDate() + 60);
  expiry.setHours(23, 59, 59, 999);
  return expiry.toISOString();
};
const libreDeudaEstadoVigencia = (request?: DeclarationData["libreDeudaSolicitud"]) => {
  const venceAt = libreDeudaVenceAt(request); if (!venceAt) return null;
  const remainingMs = new Date(venceAt).getTime() - Date.now();
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const expiryDay = new Date(venceAt); expiryDay.setHours(0, 0, 0, 0);
  const remainingDays = Math.max(0, Math.round((expiryDay.getTime() - today.getTime()) / 86400000));
  if (remainingMs < 0) return { tone: "expired", venceAt, label: "Certificado vencido", detail: "La vigencia finalizó" };
  if (remainingDays <= 7) return { tone: "expiring", venceAt, label: "Próximo a vencer", detail: remainingDays === 0 ? "Vence hoy" : `Vence en ${remainingDays} día${remainingDays === 1 ? "" : "s"}` };
  return { tone: "valid", venceAt, label: "Certificado vigente", detail: `Restan ${remainingDays} días` };
};

export default function LibreDeudaPanel({ declarations, onUpdate, onClose }: Props) {
  const [liveDeclarations, setLiveDeclarations] = useState(declarations);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [selectedRecord, setSelectedRecord] = useState<DeclarationData | null>(null);
  const [message, setMessage] = useState(""); const [search, setSearch] = useState(""); const [busy, setBusy] = useState(false); const [paymentReceipt, setPaymentReceipt] = useState<{ url: string; name: string } | null>(null);
  const readPaymentReceipt = (file: File) => new Promise<{ url: string; name: string }>((resolve, reject) => {
    if (file.size > 5 * 1024 * 1024) { reject(new Error('El comprobante no puede superar 5 MB.')); return; }
    const reader = new FileReader(); reader.onerror = () => reject(new Error('No se pudo leer el comprobante.')); reader.onload = () => resolve({ url: String(reader.result || ''), name: file.name }); reader.readAsDataURL(file);
  });
  useEffect(() => setLiveDeclarations(declarations), [declarations]);
  useEffect(() => { let active = true; let inFlight = false; const refresh = async () => { if (inFlight) return; inFlight = true; try { const fresh = await loadServerRecords(); if (active) setLiveDeclarations(fresh); } catch (error) { console.warn("No se pudieron actualizar las solicitudes de Libre Deuda", error); } finally { inFlight = false; } }; void refresh(); const interval = window.setInterval(() => void refresh(), 3000); return () => { active = false; window.clearInterval(interval); }; }, []);
  const requests = useMemo(() => liveDeclarations.filter(d => d.libreDeudaSolicitud?.submittedAt), [liveDeclarations]);
  const summary = useMemo(() => ({ pending: requests.filter(d => d.libreDeudaSolicitud?.estado === "PENDIENTE" || !d.libreDeudaSolicitud?.estado).length, approved: requests.filter(d => d.libreDeudaSolicitud?.estado === "APROBADO").length, rejected: requests.filter(d => d.libreDeudaSolicitud?.estado === "RECHAZADO").length }), [requests]);
  const filteredRequests = useMemo(() => { const q = search.trim().toLowerCase(); if (!q) return requests; return requests.filter(d => [d.dni, d.matricula, d.nombres, d.apellido, `${d.apellido} ${d.nombres}`, `${d.nombres} ${d.apellido}`].some(v => String(v || "").toLowerCase().includes(q))); }, [requests, search]);
  const address = (d: DeclarationData) => [d.domicilioActual, d.numeracionDomicilioActual ? `N° ${d.numeracionDomicilioActual}` : "", d.municipioLocalidad].filter(Boolean).join(" · ");
  const download = async (d: DeclarationData, certificate = false) => { const r = d.libreDeudaSolicitud; if (!r) return; try { let url = certificate ? r.certificadoUrl : (r.comprobantePagoUrl || r.comprobanteColegiadoUrl); let name = certificate ? (r.certificadoNombre || `Certificado_Libre_Deuda_${d.dni}.pdf`) : (r.comprobantePagoNombre || r.comprobanteColegiadoNombre || "comprobante-pago"); if (!url) { const full = await loadServerRecord(d.id); const rr = full.libreDeudaSolicitud; url = certificate ? rr?.certificadoUrl : (rr?.comprobantePagoUrl || rr?.comprobanteColegiadoUrl); name = certificate ? (rr?.certificadoNombre || name) : (rr?.comprobantePagoNombre || rr?.comprobanteColegiadoNombre || name); } if (!url && certificate) { const { generateAutomaticCertificates } = await import("../utils/certificates"); const generated = generateAutomaticCertificates(d, { libreDeudaApprovalDate: r.revisadoAt, libreDeudaExpiryDate: r.venceAt }); url = generated.eticaUrl; name = generated.eticaNombre || name; } if (!url) throw new Error("No hay archivo disponible."); const a = document.createElement("a"); a.href = String(url); a.download = name; a.target = "_blank"; document.body.appendChild(a); a.click(); a.remove(); } catch (error) { window.alert(error instanceof Error ? error.message : "No se pudo descargar el archivo."); } };
  const review = async (d: DeclarationData) => { setSelectedId(d.id); setSelectedRecord(d); setMessage(""); try { setSelectedRecord(await loadServerRecord(d.id)); } catch (error) { console.warn("No se pudo cargar el detalle de Libre Deuda", error); } };
  const resolve = async (d: DeclarationData, approved: boolean) => { const r = d.libreDeudaSolicitud; if (!r || (!approved && !message.trim())) { window.alert(approved ? "No se encontró la solicitud." : "Ingrese el motivo del rechazo."); return; } if (approved && !paymentReceipt?.url) { window.alert("Adjunte el comprobante de pago de Administración antes de aprobar."); return; } setBusy(true); try { const now = argentinaNow(); const expiry = new Date(now); expiry.setDate(expiry.getDate() + 60); expiry.setHours(23, 59, 59, 999); let certUrl = "", certName = ""; if (approved) { const { generateAutomaticCertificates } = await import("../utils/certificates"); const generated = generateAutomaticCertificates(d, { libreDeudaApprovalDate: now, libreDeudaExpiryDate: expiry.toISOString() }); certUrl = generated.eticaUrl; certName = generated.eticaNombre; } await onUpdate({ ...d, libreDeudaSolicitud: { ...r, estado: approved ? "APROBADO" : "RECHAZADO", revisadoAt: now, venceAt: approved ? expiry.toISOString() : "", mensajeAdmin: message.trim(), certificadoUrl: certUrl, certificadoNombre: certName, comprobantePagoUrl: approved ? paymentReceipt?.url || "" : "", comprobantePagoNombre: approved ? paymentReceipt?.name || "" : "", historial: approved ? r.historial : [...(r.historial || []), { estado: "RECHAZADO", mensaje: message.trim(), fecha: now }] } }); try { await notifyLibreDeudaResolution(d.id, approved, message.trim()); } catch (error) { console.error("No se pudo enviar el correo de Libre Deuda", error); } setSelectedId(null); setSelectedRecord(null); } catch (error) { window.alert(error instanceof Error ? error.message : "No se pudo resolver la solicitud."); } finally { setBusy(false); } };
  const remove = async (d: DeclarationData) => { if (!window.confirm("¿Eliminar esta solicitud de Libre Deuda?")) return; try { await onUpdate(await deleteLibreDeudaRequest(d.id)); } catch (error) { window.alert(error instanceof Error ? error.message : "No se pudo eliminar la solicitud."); } };
  return <section className="cokifimi-libre-deuda-panel" aria-label="Solicitudes de libre deuda">
    <header className="cokifimi-libre-deuda-header"><div><p>GESTIÓN ADMINISTRATIVA</p><h1>Solicitudes de Libre Deuda</h1><span>Revise, acepte o rechace las solicitudes recibidas desde el panel del colegiado.</span></div><button type="button" onClick={onClose} aria-label="Cerrar"><X /></button></header>
    <div className="cokifimi-libre-deuda-summary"><article className="is-pending"><span><Clock3 /></span><div><small>Pendientes</small><strong>{summary.pending}</strong></div></article><article className="is-approved"><span><CheckCircle2 /></span><div><small>Aprobadas</small><strong>{summary.approved}</strong></div></article><article className="is-rejected"><span><FileX2 /></span><div><small>Rechazadas</small><strong>{summary.rejected}</strong></div></article></div>
    <div className="cokifimi-libre-deuda-search"><input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por DNI, nombre o matrícula" /><span>{filteredRequests.length} de {requests.length} solicitudes</span></div>
    <div className="cokifimi-libre-deuda-list">{filteredRequests.map(d => { const r = d.libreDeudaSolicitud!; const ok = r.estado === "APROBADO"; const rejected = r.estado === "RECHAZADO"; const v = ok ? libreDeudaEstadoVigencia(r) : null; return <article key={d.id} className={`cokifimi-libre-deuda-row ${ok ? "is-approved" : rejected ? "is-rejected" : ""}`}><div className="cokifimi-libre-deuda-avatar"><RecordPhoto recordId={d.id} name={`${d.nombres} ${d.apellido}`} /></div><div className="cokifimi-libre-deuda-person"><strong>{d.apellido}, {d.nombres}</strong><span>DNI {d.dni} · M.P. {d.matricula}</span><small>Solicitud: {dateTime(r.submittedAt)}</small>{r.revisadoAt && <small>Aprobación: {dateTime(r.revisadoAt)}</small>}<div className="cokifimi-libre-deuda-contact"><span><MapPin /> {address(d)}</span><span><Phone /> {d.celular || d.telefono || "Teléfono no informado"}</span><span><Mail /> {d.email || "Correo no informado"}</span></div></div>{v && <div className={`cokifimi-libre-deuda-validity is-${v.tone}`}><Clock3 /><div><small>{v.label}</small><strong>{date(v.venceAt)}</strong><span>{v.detail}</span></div></div>}<div className="cokifimi-libre-deuda-row-actions"><span className={`cokifimi-libre-deuda-status ${ok ? "is-approved" : rejected ? "is-rejected" : "is-pending"}`}>{ok ? <><CheckCircle2 /> Aprobada</> : rejected ? <><FileX2 /> Rechazada</> : <><Clock3 /> Pendiente</>}</span>{r.estado === "PENDIENTE" && r.historial?.length ? <span className="cokifimi-libre-deuda-resubmitted-tag">Reenviada tras rechazo</span> : null}{ok ? <><button type="button" className="cokifimi-libre-deuda-download" onClick={() => void download(d)}><Download /> Descargar comprobante</button><button type="button" className="cokifimi-libre-deuda-download" onClick={() => void download(d, true)}><Download /> Descargar certificado</button></> : <button type="button" className="cokifimi-libre-deuda-review" onClick={() => void review(d)}>Revisar</button>}<button type="button" className="cokifimi-libre-deuda-delete" onClick={() => void remove(d)}><Trash2 /> Eliminar solicitud</button></div></article>; })}</div>
    {selectedId && (() => { const d = selectedRecord?.id === selectedId ? selectedRecord : liveDeclarations.find(x => x.id === selectedId); if (!d) return null; const r = d.libreDeudaSolicitud; const receipt = r?.comprobanteColegiadoUrl || r?.comprobantePagoUrl || ""; const name = r?.comprobanteColegiadoNombre || r?.comprobantePagoNombre || "comprobante-pago"; return createPortal(<div className="cokifimi-libre-deuda-modal"><div className="cokifimi-libre-deuda-dialog"><button type="button" onClick={() => setSelectedId(null)} aria-label="Cerrar"><X /></button><h2>Resolver Libre Deuda</h2><strong>{d.apellido}, {d.nombres}</strong>{r?.historial?.length ? <section className="cokifimi-libre-deuda-history"><strong>Historial de rechazos anteriores</strong>{r.historial.map((x, i) => <article key={i}><span>{dateTime(x.fecha)}</span><p>{x.mensaje}</p></article>)}</section> : null}{receipt ? <section className="cokifimi-libre-deuda-member-receipt-preview"><strong>Comprobante enviado por el colegiado</strong><span>{name}</span>{receipt.startsWith("data:image/") ? <img src={receipt} alt="Comprobante enviado por el colegiado" /> : <iframe src={receipt} title="Comprobante enviado por el colegiado" />}<a href={receipt} download={name}><Download /> Descargar comprobante</a></section> : <p>No hay comprobante adjunto.</p>}<label>Comprobante de pago de Administración<input type="file" accept="image/*,.pdf" onChange={async e => { const file = e.target.files?.[0]; e.currentTarget.value = ""; if (!file) return; try { setPaymentReceipt(await readPaymentReceipt(file)); } catch (error) { window.alert(error instanceof Error ? error.message : "No se pudo leer el comprobante."); } }} />{paymentReceipt && <small>Archivo seleccionado: {paymentReceipt.name}</small>}</label>
<label>Mensaje administrativo<textarea value={message} onChange={e => setMessage(e.target.value)} /></label><div className="cokifimi-libre-deuda-dialog-actions"><button type="button" disabled={busy} onClick={() => void resolve(d, false)}><FileX2 /> Rechazar</button><button type="button" disabled={busy} onClick={() => void resolve(d, true)}><CheckCircle2 /> Aprobar</button></div></div></div>, document.body); })()}
  </section>;
}
